export const animeGuilds = [
  { name: "Nanto Seiken" },
  { name: "Saiyans" },
  { name: "Shinsengumi" },
  { name: "Gurren Brigade" },
  { name: "Karasuno High School Volleyball Club" },
  { name: "Kakashi's Team 7" },
  { name: "Exorcist Cram School" },
  { name: "The Chimeras" },
  { name: "Yorozuya" },
  { name: "Witch Hunter Robin" },
  { name: "Quinx Squad" },
  { name: "The Espada" },
  { name: "Luffy's Grand Fleet" },
  { name: "Celestial Being" },
  { name: "Barto Club" },
  { name: "The Zodiacs" },
  { name: "Eins, zwei, drei" },
  { name: "Mages Guild" },
  { name: "Nox Pirates" },
  { name: "Nudist Beach" },
  { name: "Seven Stars Sword Art Festival Participants" },
  { name: "Order of the Black Knights" },
  { name: "Sakamaki Vampires" },
  { name: "Kohona Elders" },
  { name: "Gekkostate" },
  { name: "Shinobi Alliance" },
  { name: "The Crew of the Going Merry" },
  { name: "The Gourmet Hunters" },
  { name: "Shinsen-gumi" },
  { name: "Mugen's Group" },
  { name: "Kingsguard" },
  { name: "The Nura Clan" },
  { name: "Katsuki Clan" },
  { name: "Soul Eater Meisters and Weapons" },
  { name: "The Ainz Ooal Gown" },
  { name: "Legendary Super Saiyans" },
  { name: "Grimoire Heart" },
  { name: "Team Rocket" },
  { name: "Ryozanpaku Dojo" },
  { name: "The Hero Association" },
  { name: "Sakaki's Ryozanpaku Dojo" },
  { name: "Bleach Visoreds" },
  { name: "The Holy Order of the North Star" },
  { name: "League of Villains" },
  { name: "Hyakkaou Private Academy Student Council" },
  { name: "Red Ribbon Army" },
  { name: "Elite Ten Council" },
  { name: "Crimson Demon Clan" },
  { name: "Team Dai-Gurren" },
  { name: "Akame's Elite Seven" },
  { name: "Sun Pirates" },
  { name: "Nara Clan" },
  { name: "Saiyan Royal Family" },
  { name: "Team Natsu" },
  { name: "The Amanto" },
  { name: "Organization for the Preservation of Order and Peace" },
  { name: "Invisible Storm" },
  { name: "The Z Fighters" },
  { name: "Levi Squad" },
  { name: "Seven Warlords of the Sea" },
  { name: "Mystogan's Guild" },
  { name: "Gourmet World" },
  { name: "Shinigami Research and Development Institute" },
  { name: "The Red Dragon Pirates" },
  { name: "Mugen Tenshin Clan" },
  { name: "Jura Neekis Guild" },
  { name: "Mist Gun's Guild" },
  { name: "Dragon Slayers" },
  { name: "The Phantom Troupe" },
  { name: "Tenrou Island Guild Members" },
  { name: "Central Knights" },
  { name: "The Enforcers" },
  { name: "Strategists" },
  { name: "Outer Moka's Group" },
  { name: "Shinsengumi Special Police" },
  { name: "Proud Immortal Demon Way" },
  { name: "Black Bulls" },
  { name: "Ainzach's Guild" },
  { name: "Revocs Corporation" },
  { name: "Tengen Toppa Gurren Lagann" },
  { name: "The Guardians of the Galaxy" },
  { name: "Class 2-F" },
  { name: "Order of the White Dragon" },
  { name: "The Shinigami" },
  { name: "Ten Commandments" },
  { name: "Espers of Academy City" },
  { name: "Wandering Tribe" },
  { name: "The Nox Pirates" },
  { name: "Twelve Demon Moons" },
  { name: "The League of Villains" },
  { name: "Great Tomb of Nazarick" },
  { name: "Swordmasters of Black Iron" },
  { name: "Fangpire Clan" },
  { name: "The Shogun's Guardians" },
  { name: "The Heavens Arena Fighters" },
  { name: "Elite Four" },
  { name: "Shinsengumi 3rd Division" },
  { name: "Hunter x Hunter Association" },
  { name: "Space Pirate Captain Harlock's Crew" },
  { name: "Yusuke's Team" },
  { name: "The Black Bulls" },
  { name: "Seven Deadly Sins of Britannia" },
  { name: "Great Holy Knights" },
  { name: "Whitebeard Pirates" },
  { name: "Sakura's Team 7" },
  { name: "The Zodiacs" },
  { name: "The Pillars" },
  { name: "League of Demon Slayer Corps" },
  { name: "The Homunculi" },
  { name: "Chimera Ant Royal Guards" },
  { name: "Royal Guard" },
  { name: "Team 10" },
  { name: "Team JNPR" },
  { name: "The Generals of the Revolutionary Army" },
  { name: "Team Guy" },
  { name: "The Inklings" },
];

// module.exports = { animeGuilds };
